name: my_health_guide
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  flutter_svg: ^1.1.5
  expandable: ^5.0.1
  get_cli: ^1.8.1
  get: 4.6.4

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: true
  ios: true

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter.ttf
  uses-material-design: true

